FROM node:18-alpine AS dev

RUN apk add --no-cache bash git

WORKDIR /app

RUN chown node:node /app

COPY --chown=node:node package.json package-lock.json* ./

USER node

RUN npm install


COPY --chown=node:node src/ ./src/
COPY --chown=node:node public/ ./public/
COPY --chown=node:node index.html tsconfig*.json vite.config.ts ./

ARG PORT=3000
ENV PORT=$PORT
EXPOSE $PORT

CMD ["npm", "run", "dev"]