FROM node:18-alpine AS dev

WORKDIR /app

RUN apk add --no-cache bash git python3 make g++

COPY --chown=node:node package.json package-lock.json* ./

RUN npm install

RUN chown -R node:node /app/node_modules /app/package-lock.json

COPY --chown=node:node index.html ./          
COPY --chown=node:node public ./public
COPY --chown=node:node src ./src
COPY --chown=node:node tsconfig*.json ./
COPY --chown=node:node vite.config.ts ./

USER node

ARG PORT=3000
ENV PORT=$PORT
EXPOSE $PORT

CMD ["npm", "run", "dev"]
